### ISSUE TITLE
Adding Links to Buttons

### ISSUE THREAD

**Issue by BKR-dev** [shinsyotta/ui4reality#1]
Hey, tried to add link to the Mating Instinct song on Bandcamp, I'm not good with HTML and CSS so hopefully, this isn't too bad.

If that is working okay, I would add more to other buttons.

**Comment by shinsyotta** [comment]
Hey Booker. I think by tomorrow I’ll have some modal windows ready for some embedded players and such. We can stick Youtube videos, etc in them.  I guess Bandcamp has embed options too.
Also thinking about whether there are any questionnaires or forms we can add to any of these buttons. For example, to teach people to use can we ask people:
Q: “What do you want to achieve?”
Q: “What is an example of a worse outcome that results from not achieving what you want”
A: “What is an example of a better outcome that results from achieving what you want”
Then you have your comparison!

BTW... Sorry for slow response. Had a workshop all day today.

**Comment by BKR-dev** [comment]
Hey Shinsy,

I added a bandcamp enbedded vor Mating Instinct inside a mating-instincts.html, I still haven't wrapped my brain around html and how to make it properly good 😄 

_Also thinking about whether there are any questionnaires or forms we can add to any of these buttons._ 

Oh yeah!

Can you add a branch that I can pull or something? I would like to try to add things and practice my html a bit 😃

**Comment by shinsyotta** [comment]
Hey @BookerVII. I had a go at solving the same problem.  See this commit: https://github.com/shinsyotta/ui4reality/commit/44da64b684ca5c3997f84efa90f831baad0d50d3

If you want to make a variation, that's fine with me. You can copy and change the modal setup function on line 216 to create a different kind of embed, and we can do alternative embeds.  Hell, we could show different ones at random.  

I created another branch you can edit.  It's here: https://github.com/shinsyotta/ui4reality/tree/sketchpad

However, I recommend you do a pull request as follows (instructions stolen and modified from https://opensource.com/article/19/7/create-pull-request-github, which was the article Google summarized for me):

1. Clone my repo to your local system.
2. Make a new branch and name it "bandcamp_by_booker" or something distinguishing.
3. Make your changes.
4. Push it back to your repo.
5. Click the Compare & pull request button on your Github.
6. Click Create pull request to open a new pull request.

**Comment by BKR-dev** [comment]
Hey!

Jup got it set up, starting looking into it and your last commit is the way to go!

So for now I got nothing but time to wait for a good idea! 😄
